### PR TITLE
Collection needs to be used

### PR DESCRIPTION
**Pull request by OskarStark**
I tried to use ArrayCollection, like said in the docs but this was not working...

### CODE REVIEW

**Comment by OskarStark** [comment]
could you please fix the GITHUB Toke problem in the travis build?

**Comment by OskarStark** [comment]
ping

**Comment by OskarStark** [comment]
hello?

**Comment by saimaz** [comment]
Thanks for the notice. Can you please rebase you PR then I could merge quickly.

**Comment by saimaz** [comment]
and include to the next patch release

**Comment by OskarStark** [comment]
I rebased the branch, can you please merge it?

**Comment by saimaz** [comment]
I will cherry-pick by myself this commit to the 5.0 branch because seems like you don't know what rebase means ;)

Thank you for the PR.

**Comment by OskarStark** [comment]
I know it, but I missed, that you already switched the branch, so I switched it back and rebased on top of it...

**Pull request merged**
