### PR TITLE
Move getting of aliases above setting fields

### PR DESCRIPTION
**Pull request by toooni**
https://github.com/ongr-io/ElasticsearchBundle/commit/90c505af939b0ec18394645758a915b9c397cb51 introduced a bug where aliases were not merged in fields.
The problem here is that the second parameter of `getAliases` is submitted by reference with the intention of using it in `fields`.
I do recommend solving this a bit different because using parameters by reference is often a bad idea and can lead to problems like this one.

However this reverts the error introduced in https://github.com/ongr-io/ElasticsearchBundle/commit/90c505af939b0ec18394645758a915b9c397cb51 and fixes https://github.com/ongr-io/ElasticsearchBundle/issues/772

### CODE REVIEW

**Comment by saimaz** [comment]
Thank you for the PR @toooni, Could you rebase your branch to 5.0? I already changed the base branch here in the PR.

**Comment by saimaz** [comment]
Tonny, sorry for notice, but merge commit is not a rebase for this PR. Maybe you could open a new PR with a new branch created from 5.0 branch?

**Comment by toooni** [comment]
@saimaz I redo the PR for 5.0

**Comment by toooni** [comment]
@saimaz done https://github.com/ongr-io/ElasticsearchBundle/pull/826

**Pull request closed without merging**
