### PR TITLE
'is' getter now is supported for documents

### LINKED ISSUE #485: Add support for document getters with "is" prefix
It's common practice to have `setFoo()` and `isFoo()` methods for boolean variables. Currently only `get` prefix is supported.

Code reference: https://github.com/ongr-io/ElasticsearchBundle/blob/65d6405ccb2cbd7fb79da9ef42745e9fdd39cd0f/Mapping/DocumentParser.php#L187

### PR DESCRIPTION
**Pull request by asev**
closes #485

### CODE REVIEW

**Comment by saimaz** [comment]
I have strong doubts about is'ser. Even if we will add a support for it, we have to check only on `boolean` fields.

**Comment by mvar** [comment]
I think _is'sers_ are really useful. As @saimaz suggested, _is'ser_ should be checked only for `boolean` parameters.

**Comment by asev** [comment]
IMHO issers make code more readable. To use isser only for boolean would need to implement complex logic.
Why is it bad to check getter/isser for all properties? [twig](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Template.php#L568) and [doctrine](https://github.com/doctrine/collections/blob/master/lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php#L49) do that.

**Comment by asev** [comment]
Ok, it was easier than I expected. So issers will be used for booleans only.

**Comment by saimaz** [comment]
So before the merge we need to solve the question if we need to support both - isser and getter together.

**Comment by mvar** [comment]
@saimaz are you talking about `boolean` fields only? If so, I think we should support both _issers_ and _getters_.

**Comment by saimaz** [comment]
Ok. it was only a suggestions, but seems like it's completely enough to have a way to get and set the data. It's no matter if it's isser or getter.

**Pull request merged**
