### PR TITLE
[Bugfix] Dont set filtered query into endpoint during normalization

### PR DESCRIPTION
**Pull request by martiis**
If same search happens to be executed twice, then in second query we would see filtered query within a filtered query with same filters.

This issue also slows down query execution time.

** EDITED **

### CODE REVIEW

**Comment by mvar** [comment]
@martiis could you add test case for this issue? As far as I understand it's enough to normalize query twice and check if results are equal, right?

> This also slows down query execution time.

The issue or the solution? :) I guess the issue. Please be more specific next time.

**Comment by martiis** [comment]
1. Yes
2. Ok ;)

**Comment by saimaz** [comment]
@martiis can you open the same PR to the DSL library? Of course, we will merge and release the `0.*` but it would be helpful also in a new version ;)

**Comment by saimaz** [comment]
@martiis could you remove python docs building part in travis? Then I could merge this PR.

**Comment by martiis** [comment]
I've removed it.

**Comment by saimaz** [comment]
The tests are still failing. I'm not sure that for 0.10 version this change is actual. If I'm wrong please reopen this PR with fixed test case.

**Pull request closed without merging**
