### PR TITLE
Manager: typehints added

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by martiis** [comment]
Hi @TomasVotruba, thanks for the touches, but we had unit some tests that did not use Connection and just `null` was passed. Would be great if they would be changed also!

**Comment by TomasVotruba** [comment]
@martiis Sure. I'll look on it.

**Comment by saimaz** [comment]
As @martiis wrote this is the reason and not the only one why we didn't add type hinting. Closing for now. @TomasVotruba If you will find a better solution feel free to reopen.

**Comment by TomasVotruba** [comment]
@saimaz For there use cases, null objects are used.

**Pull request closed without merging**
