### PR TITLE
Fix the exception of the case that an object field is empty & non multiple.

### PR DESCRIPTION
**Pull request by ndinh215**
The issue #459 was fixed. Please help me to review this patch.
Thanks.

### CODE REVIEW

**Comment by saimaz** [comment]
@ndinh215 first of all we should try to not reduce code coverage with introduced changes. Can you provide a unit test case for the problem?

**Comment by ndinh215** [comment]
Yup, I will create an unit testcase in Tests/Functional/Result/DocumentIteratorTest and alert you to review again. Thanks.

**Comment by ndinh215** [comment]
Here is the test case for this issue: https://github.com/ndinh215/ElasticsearchBundle/commit/090b65f565cc36f55664fa7f08d1a871ab3ea723. Thanks.

**Comment by patie** [comment]
i think this is problem again in v7, i have setter setImage(?Image $image); and i give error

`Product::setImage() must be an instance of App\\Elastic\\Document\\Advert\\Image or null, instance of ONGR\\ElasticsearchBundle\\Result\\ObjectIterator given`

**Pull request merged**
