### PR TITLE
sf3 support

### PR DESCRIPTION
**Pull request by emgiezet**
when this will be merged: https://github.com/ongr-io/ElasticsearchDSL/pull/38
we can enable support for sf3 in this bundle ;)

yaaay

### CODE REVIEW

**Comment by saimaz** [comment]
@emgiezet can you change dependency here by https://github.com/ongr-io/ElasticsearchDSL/pull/38 feedback?

**Comment by emgiezet** [comment]
ok the DSL is mergerd

**Comment by saimaz** [comment]
Cool, but can you do the same changes as in DSL? 

Change dependency to `~2.7|~3.0`

**Comment by emgiezet** [comment]
done deal!

**Pull request merged**
