### PR TITLE
Add condition to ignore unused managers in TerminateListener

### PR DESCRIPTION
**Pull request by esynaps**
Related to https://github.com/ongr-io/ElasticsearchBundle/issues/877

### CODE REVIEW

**Comment by esynaps** [comment]
The error in the build is unrelated to the PR : 

>  [ErrorException]          
>   Undefined index: version  

`The command "composer require --no-update symfony/symfony:${SYMFONY}" failed and exited with 1 during .`

**Comment by alexandre-le-borgne** [comment]
Can we have news?

**Comment by saimaz** [comment]
for 5.2 branch CI seems corrupted.

**Comment by esynaps** [comment]
The problem is still present and very restrictive. And considering the source code, it does not seem to have been fixed in 6.*.

**Pull request merged**
