### PR TITLE
Instance Cache added to DocumentParser::parse()

### PR DESCRIPTION
**Pull request by carlcasbolt**
- I've discovered that this method was being called a lot of times when indexing large volumes of documents with my bulk indexer code.
- Constantly parsing a Reflection class was becoming too costly so I've added an instance cache to store the document information.

### CODE REVIEW

**Comment by saimaz** [comment]
Nice catch @carlcasbolt. Thank you for the PR.

**Comment by saimaz** [comment]
I changed the base to 5.0, could you please rebase your PR branch accordingly?

**Comment by carlcasbolt** [comment]
rebasing now

**Comment by carlcasbolt** [comment]
done

**Pull request merged**
