### PR TITLE
index creation with Elasticsearch 2.0

### LINKED ISSUE #493: Investigate _ttl behaviour with ES 2.0
We got complains that on ES 2.0 it is impossible to create mapping because of '_ttl' field.

[Official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-ttl-field.html) states that "implementation is deprecated".

Full exception:
```json
{
   "error":{
      "root_cause":[
         {
            "type":"mapper_parsing_exception",
            "reason":"mapping [articles]"
         }
      ],
      "type":"mapper_parsing_exception",
      "reason":"mapping [articles]",
      "caused_by":{
         "type":"illegal_argument_exception",
         "reason":"Mapper for [_ttl] conflicts with existing mapping in other types:\n[mapper [_ttl] cannot be changed from type [string] to [long]]"
      }
   },
   "status":400
}
```

### PR DESCRIPTION
**Pull request by asev**
Also ManagerTest case fixed. Before this ttl was null and null is less than 1+.
closes #493

### CODE REVIEW

**Comment by mvar** [comment]
This looks like a hack. What if we need to exclude other fields to? Actually we need! Currently we send to Elasticsearch not only `_ttl`, but also `_id`, `_score` and `_parent`. We shouldn't.

Maybe we could create separate annotation for such fields?

CC @saimaz @murnieza

**Comment by saimaz** [comment]
This is definitelly a hack. No way we can do like this. Let's think again.

**Comment by asev** [comment]
Thank you, @mvar. This is exactly why I created this pull request. I didn't like my solution, but it was all I got. It was more like discussion starter.

**Comment by saimaz** [comment]
Closing this PR because it has to be implemented totaly different.

**Pull request closed without merging**
