### PR TITLE
Add isser for boolean properties.

### PR DESCRIPTION
**Pull request by fattouchsquall**
Hello @saimaz,

We can close the other PR https://github.com/ongr-io/ElasticsearchBundle/pull/781, i created a new one from branch 5.0.

### CODE REVIEW

**Comment by saimaz** [comment]
Cool, thanks for the PR.

**Comment by fattouchsquall** [comment]
Hello @saimaz,

Can you check plz my fix for the case when using document_dir: Document\SubDocument,

Thanks

**Comment by saimaz** [comment]
Good point. Would be really great to have a test case for this as well.

**Comment by fattouchsquall** [comment]
i'm on it

**Comment by fattouchsquall** [comment]
@saimaz,

I've added tests for this fix. Can you check them plz?

**Comment by saimaz** [comment]
There are already 2 documents in the custom fixtures dir, you can take as an example: `Tests/app/fixture/TestBundle/Entity/Product.php`. In that case, we don't need to introduce a new one.

**Comment by fattouchsquall** [comment]
Done @saimaz

**Pull request merged**
