### PR TITLE
Fix cache checking

### PR DESCRIPTION
**Pull request by norkunas**

### CODE REVIEW

**Comment by einorler** [comment]
Why did you duplicate the condition?

**Comment by norkunas** [comment]
Accidentally :/

**Comment by weburnit** [comment]
2previous PR has fixed this one @norkunas !

**Comment by norkunas** [comment]
@weburnit this is the different method i've updated

**Comment by norkunas** [comment]
https://github.com/ongr-io/ElasticsearchBundle/blob/master/Mapping/MetadataCollector.php#L344 so the branches are different?

**Pull request closed without merging**
