### PR TITLE
implemented the display of ongr_es performance in Symfony profiler

### LINKED ISSUE #616: Show profiler data under "Execution timeline"
It would be nice to see Elasticsearch queries and execution time in profiler's _Execution timeline_. Similar to Doctrine. Sorry, no image, but I hope you get the idea.

### PR DESCRIPTION
**Pull request by einorler**
closes #616

### CODE REVIEW

**Comment by saimaz** [comment]
I really don't like that we need to introduce `ManagerFactoryPass` for this feature. @einorler is this the only way to implement it?

**Comment by einorler** [comment]
I will check if I can get round the problem

**Comment by einorler** [comment]
I removed the Pass, extension is now handling everything that's needed here

**Comment by saimaz** [comment]
Can you rebase PR

**Pull request merged**
